module.exports = {
  "BASE": "httpsz://www.jwnice.com/h5/saoxing/", //资源路径
  "imageList": [
    "yhj/0.png",
    "yhj/1.png",
    "yhj/2.png",
    "yhj/3.png",
    "yhj/4.png",
    "yhj/5.png",
    "yhj/6.png",
    "yhj/7.png",
    "yhj/8.png",
    "yhj/9.png",
    "yhj/10.png",
    "yhj/11.png",
    "yhj/12.png",
    "yhj/13.png",
    "yhj/14.png",
    "yhj/15.png",
    "yhj/16.png",
    "yhj/17.png",
  ],
  "index": [
    "xxtitle/0.png",
    "xxtitle/1.png",
    "xxtitle/2.png",
    "xxtitle/3.png",
    "xxtitle/4.png",
    "xxtitle/5.png",
    "xxtitle/6.png",
    "xxtitle/7.png",
    "xxtitle/8.png",
    "xxtitle/9.png",
    "xxtitle/10.png",
    "xxtitle/11.png",
  ]
}